### ISSUE TITLE
memory leaks on playback

### ISSUE THREAD

**Issue by RogerLaw** [shin1m/alexaagent#6]
EDIT: the reconnecting issue might be my own fault, ignore it.

---
## asio.ssl error, and then segmentation fault

when I leave the program running for a while, it will throw an error:

@session(0x7b82e8) on error: asio.ssl error   |
reconnecting...
session(0x7b82e8) created
directives GET(0x82eb20) on close: 2
@session(0x7b82e8) on error: asio.ssl error   |
reconnecting...
Segmentation fault

**Comment by shin1m** [comment]
I fixed memory leak during playing audio.
I'm not sure it is relevant to this problem.
Was it playing audio when the error happened?
Best regards,

**Comment by RogerLaw** [comment]
Yes, I also noticed the VSZ increasing while playback. now this memory leak fixed.
I will try to find a way to reproduce the reconnection crash problem, maybe it's my bad since I modified some codes and not fully tested yet.

**Comment by RogerLaw** [comment]
regarding the memory leak, I think this might be a source?

```
~t_callback_audio_source()
{
    av_freep(&v_io->buffer);
    av_free(v_io);
}
```

because t_callback_audio_source is derived from t_audio_source, this desstructor don't have a chance to run.

**Comment by shin1m** [comment]
You nailed it! I forgot to make them virtual.
I've pushed the fix.
Thank you.

**Comment by RogerLaw** [comment]
shall we add    av_free(v_codec) to ~t_audio_source() ?
it seems this also helps.

there are still some memory leaks on decode(), I haven't figure out where yet (my mod use swswr_convert).

**Comment by shin1m** [comment]
OK, I will fix it. Maybe I have to consider the way to destruct them again.
Thank you.

**Comment by RogerLaw** [comment]
which ffmpeg are you using? it seems I don't AVStream.codecpar support. I am using ffmpeg 2.8.7

**Comment by shin1m** [comment]
I'm using ffmpeg 3.1.3. I'm sorry but Arch Linux delivers the latest.

Hmm, I modified so because I found [this post](https://ffmpeg.org/pipermail/ffmpeg-cvslog/2016-April/099152.html).

**Comment by RogerLaw** [comment]
thanks, I will upgrade to latest ffmpeg :)

**Comment by shin1m** [comment]
I would close this.
If you still have any, please let me know.
Thank you.
